#!/bin/sh

CONF="/home/zero/.aria2/aria2.conf"
list=`wget -qO- https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt|awk NF|sed ":a;N;s/\n/,/g;ta"`
if [ -z "`grep "bt-tracker" ${CONF}`" ]; then
sed -i ‘$a bt-tracker=’${list} ${CONF}
echo add……
else
sed -i "s@bt-tracker.*@bt-tracker=$list@g" ${CONF}
echo update……
fi
